[package]
name = "mongodb-test-client"
version = "0.1.0"
authors = ["Clément Marescaux <cmarescaux@hotmail.com>"]

[dependencies]
rayon = "*"
serde = "*"
ron = "*"
bson = "0.11.1"
# mongodb = "0.3.10"
mongo_driver = "0.12.1"